LMS_Demo/Controllers/DashboardController.cs
using LMS_Demo.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;


namespace LMS_Demo.Controllers
{
    public class DashboardController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public DashboardController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult StudentDashbord()
        {
            ViewBag.userid = _userManager.GetUserName(HttpContext.User);
          
            //var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View();
        }
        public IActionResult FacilitatorDashbord()
        {
            return View();

        }
        public IActionResult HODDashbord()
        {
            return View();

        }
        public IActionResult AdminDashbord()
        {
            return View();

        }
        public IActionResult SponsorDashbord()
        {
            return View();

        }
    }
}

LMS_Demo/Controllers/QuizController.cs
using LMS_Demo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace LMS_Demo.Controllers
{
    public class QuizController : Controller
    {
        private readonly ApplicationDBContext _db;
        public QuizController(ApplicationDBContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Quizzes.ToListAsync());
        }
    }
}

LMS_Demo/Controllers/SubmitAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using LMS_Demo.Data;
using LMS_Demo.Models;
using Microsoft.AspNetCore.Identity;

namespace LMS_Demo.Controllers
{
    public class SubmitAssignmentsController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;


        public SubmitAssignmentsController(ApplicationDBContext db, IWebHostEnvironment hostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

        }

        // GET: SubmitAssignments
        public async Task<IActionResult> Index()
        {
            var relationshipsContext = _db.SubmitAssignment.Include(s => s.Assesment).Include(s => s.Student);
            return View(await relationshipsContext.ToListAsync());
        }

        // GET: SubmitAssignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submitAssignment = await _db.SubmitAssignment
                .Include(s => s.Assesment)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.SubmitID == id);
            if (submitAssignment == null)
            {
                return NotFound();
            }

            return View(submitAssignment);
        }

        // GET: SubmitAssignments/Create
        public IActionResult Create()
        {
            ViewBag.userid = _userManager.GetUserName(HttpContext.User);
       

            ViewData["AssesmentID"] = new SelectList(_db.Assesments, "AssesmentID", "AssesmentID");
            ViewData["StudentID"] = new SelectList(_db.Students, "StudentID", "StudentID");
            return View();
        }

        // POST: SubmitAssignments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubmitID,StudentID,AssesmentID,File,SubmissionDate")] SubmitAssignment submitAssignment)
        {
            if (ModelState.IsValid)
            {
                //save File
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(submitAssignment.File.FileName);
                string extention = Path.GetExtension(submitAssignment.File.FileName);
                submitAssignment.FilePath = fileName + DateTime.Now.ToString("yyyy-MM-dd") + extention;
                string path = Path.Combine(wwwRootPath + "/Submissions/", fileName);
                String now = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                submitAssignment.SubmissionDate = DateTime.Parse(now);
                using (var fileStream = new FileStream(path, FileMode.Create))

                {
                    await submitAssignment.File.CopyToAsync(fileStream);
                }

                _db.Add(submitAssignment);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.userid = _userManager.GetUserName(HttpContext.User);
            ViewData["AssesmentID"] = new SelectList(_db.Assesments, "AssesmentID", "AssesmentID", submitAssignment.AssesmentID);
            ViewData["StudentID"] = new SelectList(_db.Students, "StudentID", "StudentID", submitAssignment.StudentID);
            return View(submitAssignment);
        }

       public FileResult Download(string fileName)
       {
            string path = Path.Combine(this._hostEnvironment.WebRootPath, "Submissions/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", fileName);
       }



   

        // GET: SubmitAssignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submitAssignment = await _db.SubmitAssignment.FindAsync(id);
            if (submitAssignment == null)
            {
                return NotFound();
            }
            ViewData["AssesmentID"] = new SelectList(_db.Assesments, "AssesmentID", "AssesmentID", submitAssignment.AssesmentID);
            ViewData["StudentID"] = new SelectList(_db.Students, "StudentID", "StudentID", submitAssignment.StudentID);
            return View(submitAssignment);
        }

        // POST: SubmitAssignments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SubmitID,StudentID,AssesmentID,FilePath,SubmissionDate")] SubmitAssignment submitAssignment)
        {
            if (id != submitAssignment.SubmitID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(submitAssignment);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubmitAssignmentExists(submitAssignment.SubmitID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AssesmentID"] = new SelectList(_db.Assesments, "AssesmentID", "AssesmentID", submitAssignment.AssesmentID);
            ViewData["StudentID"] = new SelectList(_db.Students, "StudentID", "StudentID", submitAssignment.StudentID);
            return View(submitAssignment);
        }

        // GET: SubmitAssignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submitAssignment = await _db.SubmitAssignment
                .Include(s => s.Assesment)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.SubmitID == id);
            if (submitAssignment == null)
            {
                return NotFound();
            }

            return View(submitAssignment);
        }

        // POST: SubmitAssignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var submitAssignment = await _db.SubmitAssignment.FindAsync(id);
            _db.SubmitAssignment.Remove(submitAssignment);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubmitAssignmentExists(int id)
        {
            return _db.SubmitAssignment.Any(e => e.SubmitID == id);
        }
    }
}

LMS_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LMS_Demo</title>
    <link href="~/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/theme/css/sb-admin-2.min.css" rel="stylesheet">

    

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <link href="~/themes/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/themes//lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <link href="~/themes/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/themes/css/style.css" rel="stylesheet" />
</head>
<body >
    
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>




    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/themes/lib/wow/wow.min.js"></script>
    <script src="~/themes/lib/easing/easing.min.js"></script>
    <script src="~/themes/lib/waypoints/waypoints.min.js"></script>
    <script src="~/themes/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/themes/js/main.js"></script>




    <script src="~/theme/vendor/jquery/jquery.min.js"></script>
    <script src="~/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/theme/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/theme/js/sb-admin-2.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LMS_Demo/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Student | DashBoard</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/datepicker3.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/datatables/css/datatables.bootstrap.css">
    <link rel="stylesheet" href="~/Content/Chosen/chosen.min.css">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Layout/resources/img/logo.jpg" />
    <link href="~/Content/css/styles.css" rel="stylesheet">
    

    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Dashboard</span>Student</a>
                <ul class="nav navbar-top-links navbar-right"></ul>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <div class="profile-sidebar">
            <div class="profile-userpic">
                <img src="~/Content/img/Administrator.png" class="img-responsive" alt="">
            </div>
            <div class="profile-usertitle">
                <div class="profile-usertitle-name">@User.Identity.Name</div>
                <div class="profile-usertitle-status"><span class="indicator label-success"></span>Student</div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>
        <ul class="nav menu">
            <li class="active"><a href="@Url.Action("StudentDashbord", "Dashboard")"><em class="fa fa-dashboard">&nbsp;</em> DashBoard</a></li>
          
            <li>
                <button class="collapsible"><em class="fa fa-book">&nbsp; &nbsp;</em>Quizzes</button>
                <div style="width: 100% !important" class="children content">
                    @Html.ActionLink("View Quizzes", "Index", "Quiz", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
          
                </div>
            </li>
            <li>
                <button class="collapsible"><em class="fa fa-calendar-check-o">&nbsp; &nbsp;</em>Schedule</button>
                <div style="width: 100% !important" class="children content">
                    @Html.ActionLink("Your Schedule", "ScheduleDetail", "Doctor", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
                </div>
            </li>
            <li>
                <button class="collapsible"><em class="fa fa-pencil-square-o">&nbsp; &nbsp;</em>Appointment</button>
                <div style="width: 100% !important" class="children content">
                    @Html.ActionLink("Add Appointment", "AddAppointment", "Doctor", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
                    @Html.ActionLink("Active Appointments", "ActiveAppointments", "Doctor", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
                    @Html.ActionLink("Pending Appointments", "PendingAppointments", "Doctor", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
                </div>
            </li>
            <li>
                <button class="collapsible"><em class="fa fa-cog">&nbsp; &nbsp;</em>Assesments</button>
                <div style="width: 100% !important" class="children content">
                    @Html.ActionLink("View Assessments", "AllAssesments", "AssesmentAttachments", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })
                    @Html.ActionLink("Submitted Assessments", "Index", "SubmitAssignments", null, new { @class = "list-group-item", @style = "margin: 0px -20px; font-size: 13px" })

                </div>
            </li>
            @Html.Partial("_LoginPartial")
        </ul>
    </div><!--/.sidebar-->

    <div class="col-sm-7 col-sm-offset-3 col-lg-10 col-lg-offset-2 ">
        @RenderBody()
    </div>	<!--/.main-->

    @*@Scripts.Render("~/bundles/lib")*@
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/custom.js"></script>
    <!--Script for collapse-->
    <script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click",
                function () {
                    this.classList.toggle("actives");
                    var content = this.nextElementSibling;
                    if (content.style.maxHeight) {
                        content.style.maxHeight = null;
                    } else {
                        content.style.maxHeight = content.scrollHeight + "px";
                    }
                });
        }
    </script>
    <script>
        $('.count').each(function () {
            $(this).prop('Counter', 0).animate({
                Counter: $(this).text()
            }, {
                duration: 1500,
                easing: 'swing',
                step: function (now) {
                    $(this).text(Math.ceil(now));
                }
            });
        });
    </script>
    @await RenderSectionAsync("scripts", required: false)

</body>

</html>